apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qgyd2r8qu-java-springboot
  janus-idp.io/tekton: qgyd2r8qu-java-springboot
  backstage.io/kubernetes-id: qgyd2r8qu-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: qgyd2r8qu-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
